apiVersion: v1
kind: Service
metadata:
  name: docqa-api
  namespace: docqa
  labels:
    app: docqa-ai
    component: api
spec:
  selector:
    app: docqa-ai
    component: api
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 9090
      targetPort: 9090
      name: metrics
  type: ClusterIP
